version: '3.8'
services:
  api:
    container_name: api-container
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - postgres
  postgres:
    container_name: postgres-container
    image: postgres:16.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=db
    ports:
      - '5432:5432'