version: '3.8'
services:
  api:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
    networks:
      - appnet
      - internet
      
  postgres:
    container_name: app-db
    restart: always
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=db
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - appnet

volumes:
  postgres:

networks:
  appnet:
    name: appnet
    driver: bridge
  internet:
    name: internet
    driver: bridge